kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: push github mirror
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@github.com:fmnx-ru/fmnx-dev.git
      force: false
      commit: true
      ssh_key:
        from_secret: SSHKEY
